### ISSUE TITLE
feature: include a few sample docs/ to render in the UI as techdocs

### ISSUE THREAD

**Issue by kurtaking** [backstage/demo#198]
I was looking at the demo site and noticed no examples of techdocs. I wanted to see how documentation looks with the aperture theme. 

![image](https://github.com/backstage/demo/assets/14222009/2b35a934-e4df-4cbc-8b63-2820d1d745e0)

If the demo site can support it, it would be nice to surface a few sample docs as examples. I don't mind opening a PR, but I started with an issue to see if there is a reason why that doesn't exist. 

Thanks!

**Comment by awanlin** [comment]
I think there might be a bug, there are docs for the Backstage entity -  https://demo.backstage.io/catalog/default/component/backstage/docs - but they don't show up under docs for some reason 🤔

**Comment by awanlin** [comment]
Not as issue in a fresh instance created with `npx @backstage/create-app@latest`, the Demo is currently on `1.21.0-next.2` so maybe its in one of the latest `next` releases

**Comment by awanlin** [comment]
Can replicate with latest from the main `backstage/backstage` repo. Not an issue with the Demo but going to keep this open until there is a fix 👍

**Comment by awanlin** [comment]
PR with a fix is here: https://github.com/backstage/backstage/pull/21719

**Comment by awanlin** [comment]
Going to close this as the fix has been merged, is part of the release that came out yesterday, and have been deployed today 🚀
