### ISSUE TITLE
[Catalog] Clicking a system in catalog leads to 404

### ISSUE THREAD

**Issue by iamEAP** [backstage/demo#20]
Clicking a system in the catalog leads to a 404

## Expected Behavior

It'd be great to see a nice system overview page!  Or not be linked at all, yet.

## Current Behavior

A brief blip of the outline of a page, followed by an entity not found page takeover.

## Possible Solution

- If a system page exists, let's link it / use it (or if we have a mock/comp for such a page, let's implement it!)
- If we don't have such a page yet, we should at least un-link the system in the catalog table.

## Steps to Reproduce

![404'd](https://user-images.githubusercontent.com/3496491/109126405-7db2f780-774d-11eb-91fd-e61dc6fce546.gif)

## Your Environment
https://demo.backstage.io

**Comment by OrkoHunter** [comment]
Transferred the issue to the backstage/demo repository since the problem doesn't exist in the example-app of the backstage/backstage repository (just verified by clicking on a system from catalog page). Thanks!

**Comment by timbonicus** [comment]
Fixed in #24

**Comment by OrkoHunter** [comment]
Wohoo!
