### ISSUE TITLE
bug: Images broken in TechDocs

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/demo#22]
Seems images embedded in the documentation don't display through TechDocs for the demo instance.

https://demo.backstage.io/docs/default/Component/backstage/overview/logos/

![image](https://user-images.githubusercontent.com/33203301/111559704-691fb900-8767-11eb-81a6-5add31b8e488.png)

This may be an issue more of how the microsite statically hardcodes to a path, than the demo site itself; I'm not sure.

**Comment by OrkoHunter** [comment]
Yeah the static hardcoded paths make it impossible to render them on TechDocs (and GitHub preview itself). Making them relative like the other image tabs will fix them.

https://github.com/backstage/backstage/blob/master/docs/overview/logos.md
