### ISSUE TITLE
Don't use the latest version of kroki at Dockerfile or update python in your image up to 3.10

### ISSUE THREAD

**Issue by ajax-kovtunov-o** [backstage/demo#290]
It's produces type err, cause it uses the Python 3.10 at latest release and it's incompatible with old versions
![image](https://github.com/backstage/demo/assets/123635332/98d60b36-837e-4cbc-a94e-5afe30e501c0)

**Comment by awanlin** [comment]
Hi @ajax-kovtunov-o, can you share a little more details? As you posted a screen shot and not a link it's hard for me to follow where you are coming from.

**Comment by ajax-kovtunov-o** [comment]
The plugin mcdocs kroki has released new version with 0.71, that include rely to Python 3.10 and use new features.
https://github.com/AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin

You use the latest version of this plugin at dockerfile
https://github.com/backstage/demo/blob/ca9b75448dd1b36869f539c98084e2a6bb4ce5fa/Dockerfile#L74

You can't be sure that Python version at your image is Python 3.10+.

So, try render diagram
- configure mkdocs.yaml at project
```yml
plugins:
  - techdocs-core
  - kroki:
      FileTypes:
        - svg
```

And add to any file with `uml` to your docs
```kroki-plantuml
@startuml
!theme aws-orange
@enduml

```

Then, if you use the latest version of python lib `mkdocs-kroki-plugin`, and your Python lower than Python 3.10, you will catch the TypeError. 

I suggest you to use fixed version of `mkdocs-kroki-plugin` and be sure that your Python version at docker image at least 3.10.

**Comment by awanlin** [comment]
Awesome, thanks for the details! We are only using Kroki for Mermaid and it's still working here: https://demo.backstage.io/docs/default/component/backstage-demo/examples/mermaid/. For PlantUML we are using the PlantUML itself. These are mostly to act as working examples but they need to work so this information is valuable.

**Comment by awanlin** [comment]
I am considering using what's been suggested here as an alternative: https://github.com/backstage/mkdocs-techdocs-core/issues/35#issuecomment-1779151887. Kroki is nice but for many Adopters poses security concerns with this data going out of their network and not really wanting to have to run yet another server for it
