### ISSUE TITLE
How to create app by yarn 3 without yarn 1 and migration 

### ISSUE THREAD

**Issue by node** [backstage/demo#485]
By backstage doc, it creates app by yarn 1 default, and then we can migrate it to yarn 3. 

But can I create app by yarn 3 directly now ?

**Comment by awanlin** [comment]
Hi @node, this repo is strictly for the Backstage demo site, if you need help feel free to [log an issue](https://github.com/backstage/backstage/issues) in the main Backstage repo or on the [Backstage Discord Sever](https://discord.com/invite/MUpMjP2).

As of right now Backstage still uses Yarn 1 as the default.
