### ISSUE TITLE
Mermaid Demo Page Fails to Display Diagrams

### ISSUE THREAD

**Issue by DaisukeHirabayashi** [backstage/demo#500]
The Mermaid example on the Backstage demo page is not rendering the diagrams as expected. The issue can be observed on the following page.

[Mermaid Example - Backstage Demo](https://demo.backstage.io/docs/default/component/backstage-demo/examples/mermaid/#example)

<img width="1427" alt="Screenshot 2024-07-08 at 5 40 25 PM" src="https://github.com/backstage/demo/assets/50356043/f66a3cf5-9ac2-41b2-99c1-c70e32fd2d16">

Code Reference:
https://github.com/backstage/demo/blob/master/docs/examples/mermaid.md?plain=1#L15-L20

Expected behavior:  
- The Mermaid diagrams should be rendered and visible.

Actual behavior:  
- The diagrams are not rendered.

**Comment by awanlin** [comment]
Thanks for flagging this @DaisukeHirabayashi, I had noticed this the other day as well but never had the chance to follow up, this is a good reminder. Feel free to investigate more as well if you have time and would like. 👍

**Comment by awanlin** [comment]
Just noticed this seems to be working again? 🤷

**Comment by awanlin** [comment]
Closing as we are using a different method for rendering these: https://github.com/backstage/demo/pull/542
