### ISSUE TITLE
public path serving error.

### ISSUE THREAD

**Issue by adminy** [backstage/demo#596]
I'm trying the `EXPERIMENTAL_VITE=1` option, otherwise everything else is standard.

the error is:
```
WARN Files in the public directory are served at the root path.
Instead of /public/index.html, use /index.html.
```

**Comment by awanlin** [comment]
Hi @adminy, you'll want to log this in the main Backstage repo: https://github.com/backstage/backstage/issues/new/choose

Just curious, I've noticed you have logged issues there before, why did you feel this was the place to log this issue? Just trying to gather feedback to better understand your context and flow that got you here.

**Comment by awanlin** [comment]
Going to close this as I haven't heard back.
