### ISSUE TITLE
Keeping the Demo Up to Date

### ISSUE THREAD

**Issue by awanlin** [backstage/demo#63]
It would be great if the Demo site stayed up to date with the recent release, personally keeping it up with the `next` release path would be pretty awesome! Currently it's on `1.0.1` and the latest release is at `1.5.0`.

Internally we've developed a Version Bump workflow for our Backstage instance that automates this process and creates a PR with the needed changes. We'd like to share it with the community and thought that adding it here with the demo site would help make keeping it up to date easier and give the community a concrete working example

Would this be something you would like to see contributed?

**Comment by awanlin** [comment]
@iamEAP @timbonicus @jhaals you had recent commits so figured I'd ask you for your thoughts on this?

**Comment by iamEAP** [comment]
Ooooh man, I'd personally love to see something like this.  Though I'll defer to @jhaals as chief automator and more of a primary owner of this repo.

**Comment by awanlin** [comment]
Ok, cool, thanks @iamEAP 

@jhaals, what do you think? I'd like to get this in place and working to demo at the September Contributor/Adopter sessions if possible.

**Comment by awanlin** [comment]
Alright, I've got a PR in place to add a new action/workflow that will automate the version bump process.

When you have some time @jhaals can you take a look? We might need to collaborate a little to get everything working

**Comment by jhaals** [comment]
@awanlin oh lord sorry. I realise I do not keep up with mentions on Github 😓
